// this file is generated by SCons script
#ifndef FAIF_VERSION_H
#define FAIF_VERSION_H
namespace faif {
  const int FAIF_VERSION_MAJOR = 0;
  const int FAIF_VERSION_MINOR = 43;
  const int FAIF_VERSION_COMPILATION = 000;
} //namespace faif
#endif //FAIF_VERSION_H
